###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:18-alpine As development

WORKDIR /usr/src/app

COPY ./backend/package*.json ./

RUN npm i

COPY ./backend .

COPY .env .

RUN npm run build
