/* tslint:disable */
/* eslint-disable */
/**
 * Exchange Rates
 * Exchange Rates API proxy for https://exchangerate-api.com
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RateStats
 */
export interface RateStats {
    /**
     * YYYY-MM-DD
     * @type {string}
     * @memberof RateStats
     */
    day: string;
    /**
     * Exchange Rate
     * @type {number}
     * @memberof RateStats
     */
    rate: number;
}

/**
 * Check if a given object implements the RateStats interface.
 */
export function instanceOfRateStats(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "day" in value;
    isInstance = isInstance && "rate" in value;

    return isInstance;
}

export function RateStatsFromJSON(json: any): RateStats {
    return RateStatsFromJSONTyped(json, false);
}

export function RateStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RateStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'day': json['day'],
        'rate': json['rate'],
    };
}

export function RateStatsToJSON(value?: RateStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'day': value.day,
        'rate': value.rate,
    };
}

